Update node_install

diff --git a/node_install b/node_install
--- a/node_install
+++ b/node_install
@@ -1,56 +1,98 @@
 #!/bin/bash
 
+# Step 0: Welcome
+echo "✨ Welcome! This script will prepare your server for the Quilibrium node installation. ✨"
+echo ""
+echo "Made with 🔥 by LaMat - https://quilibrium.one"
+echo "Helped by 0xOzgur.eth - https://quilibrium.space"
+echo "====================================================================================="
+echo ""
+echo "Processing... ⏳"
+sleep 7  # Add a 7-second delay
+
 # Exit on any error
 set -e
 
-# Define a function for displaying exit messages
+# Step 1: Define a function for displaying exit messages
 exit_message() {
     echo "❌ Oops! There was an error during the script execution and the process stopped. No worries!"
     echo "🔄 You can try to run the script from scratch again."
     echo "🛠️ If you still receive an error, you may want to proceed manually, step by step instead of using the auto-installer."
 }
 
-# Set a trap to call exit_message on any error
+# Step 2: Set a trap to call exit_message on any error
 trap exit_message ERR
 
-# Step 0: Welcome
-echo "✨ This script will install your Quilibrium node as a service and start it. ✨"
-echo "Made with 🔥 by LaMat (with 0xOzgur.eth help)"
-echo "Processing... ⏳"
-sleep 7  # Add a 7-second delay
-
-# Ensure Go is available
-export GOPATH=$HOME/go
-export GOROOT=/usr/local/go  # Adjust this path to where Go is installed
-export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
-
-# Check if Go is installed
-if ! command -v go &> /dev/null; then
-    echo "⚠️ Go is not installed. Please install Go and try again."
-    exit 1
+# Step 3: Check if directory ~/ceremonyclient exists, download from github 
+if [ -d ~/ceremonyclient ]; then
+    # Check if backup directory ~/backup/qnode_keys exists, if not create it
+    if [ ! -d ~/backup/qnode_keys ]; then
+        mkdir -p ~/backup/qnode_keys
+    fi
+    
+    # Check if files exist, then backup
+    if [ -f ~/ceremonyclient/node/.config/keys.yml ]; then
+        cp ~/ceremonyclient/node/.config/keys.yml ~/backup/qnode_keys/
+        echo "✅ Backup of keys.yml created in ~/backup/qnode_keys folder"
+    fi
+    
+    if [ -f ~/ceremonyclient/node/.config/config.yml ]; then
+        cp ~/ceremonyclient/node/.config/config.yml ~/backup/qnode_keys/
+        echo "✅ Backup of config.yml created in ~/backup/qnode_keys folder"
+    fi
 fi
 
-# Download Ceremonyclient
-echo "⬇️ Downloading Ceremonyclient..."
+# Step 4: Download Ceremonyclient
+echo "⏳Downloading Ceremonyclient"
 sleep 1  # Add a 1-second delay
 cd ~
-git clone https://github.com/QuilibriumNetwork/ceremonyclient.git
+if [ -d "ceremonyclient" ]; then
+  echo "Directory ceremonyclient already exists, skipping git clone..."
+else
+  until git clone https://source.quilibrium.com/quilibrium/ceremonyclient.git \
+        || git clone https://git.quilibrium-mirror.ch/agostbiro/ceremonyclient.git \
+        || git clone https://github.com/QuilibriumNetwork/ceremonyclient.git; do
+    echo "Git clone failed, retrying..."
+    sleep 2
+  done
+fi
 
-# Build Ceremonyclient
-echo "🔧 Building Ceremonyclient..."
-sleep 1  # Add a 1-second delay
-cd ~/ceremonyclient/node
-GOEXPERIMENT=arenas go install ./...
+cd ~/ceremonyclient/
+git checkout release
 
-# Build Ceremonyclient qClient
-echo "🔨 Building qClient..."
+# Set up environment variables (redundant but solves the command go not found error)
+export GOROOT=/usr/local/go
+export GOPATH=$HOME/go
+export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
+
+# Step 4.1: Build Ceremonyclient qClient
+echo "⏳ Building qCiient..."
 sleep 1  # Add a 1-second delay
 cd ~/ceremonyclient/client
 GOEXPERIMENT=arenas go build -o qclient main.go
 
-# Create Ceremonyclient Service
-echo "🛠️ Creating Ceremonyclient Service..."
-sleep 1  # Add a 1-second delay
+# Step 5:Determine the ExecStart line based on the architecture
+# Get the current user's home directory
+HOME=$(eval echo ~$HOME_DIR)
+
+# Use the home directory in the path
+NODE_PATH="$HOME/ceremonyclient/node"
+EXEC_START="$NODE_PATH/release_autorun.sh"
+
+# Step 6:Create Ceremonyclient Service
+echo "⏳ Creating Ceremonyclient Service"
+sleep 2  # Add a 2-second delay
+
+# Check if the file exists before attempting to remove it
+if [ -f "/lib/systemd/system/ceremonyclient.service" ]; then
+    # If the file exists, remove it
+    rm /lib/systemd/system/ceremonyclient.service
+    echo "ceremonyclient.service file removed."
+else
+    # If the file does not exist, inform the user
+    echo "ceremonyclient.service file does not exist. No action taken."
+fi
+
 sudo tee /lib/systemd/system/ceremonyclient.service > /dev/null <<EOF
 [Unit]
 Description=Ceremony Client Go App Service
@@ -59,30 +101,28 @@ Description=Ceremony Client Go App Service
 Type=simple
 Restart=always
 RestartSec=5s
-WorkingDirectory=/root/ceremonyclient/node
-Environment=GOEXPERIMENT=arenas
-ExecStart=/root/go/bin/node ./...
+WorkingDirectory=$NODE_PATH
+ExecStart=$EXEC_START
 
 [Install]
 WantedBy=multi-user.target
 EOF
 
-# Reload systemd manager configuration
+# Step 7: Start the ceremonyclient service
+echo "✅ Starting Ceremonyclient Service"
+
+sleep 2  # Add a 2-second delay
 sudo systemctl daemon-reload
+systemctl enable ceremonyclient
+service ceremonyclient start
 
-# Start the ceremonyclient service
-echo "🚀 Starting Ceremonyclient Service..."
-sleep 1  # Add a 1-second delay
-sudo systemctl enable ceremonyclient
-sudo systemctl start ceremonyclient
-
-# Final messages
+# Step 8: Final messages
 echo "🎉 Now your node is starting!"
 echo "🕒 Let it run for at least 30 minutes to generate your keys."
 echo ""
 echo "🔐 You can logout of your server if you want and login again later."
 echo "🔒 After 30 minutes, backup your keys.yml and config.yml files."
-echo "ℹ️ More info about this in the online guide: https://iri.quest/quilibrium-node-guide"
+echo "ℹ️ More info about this in the online guide: https://docs.quilibrium.one"
 echo ""
 echo "📜 Now I will show the node log below..."
 echo "To exit the log, just type CTRL +C."
