Update version_update

diff --git a/version_update b/version_update
--- a/version_update
+++ b/version_update
@@ -1,23 +1,92 @@
 #!/bin/bash
 
-# Step 0: Welcome
-echo "This script is made with ❤️ by https://quilibrium.space @ 0xOzgur.eth"
-echo "⏳Enjoy and sit back while you are upgrading your Quilibrium Node to v1.4.18!"
-echo "The script is prepared for Ubuntu machines. If you are using another operating system, please check the compatibility of the script."
-echo "⏳Processing..."
-sleep 10  # Add a 10-second delay
+cat << "EOF"
 
-# Stop the ceremonyclient service
-service ceremonyclient stop
+                    QQQQQQQQQ       1111111   
+                  QQ:::::::::QQ    1::::::1   
+                QQ:::::::::::::QQ 1:::::::1   
+               Q:::::::QQQ:::::::Q111:::::1   
+               Q::::::O   Q::::::Q   1::::1   
+               Q:::::O     Q:::::Q   1::::1   
+               Q:::::O     Q:::::Q   1::::1   
+               Q:::::O     Q:::::Q   1::::l   
+               Q:::::O     Q:::::Q   1::::l   
+               Q:::::O     Q:::::Q   1::::l   
+               Q:::::O  QQQQ:::::Q   1::::l   
+               Q::::::O Q::::::::Q   1::::l   
+               Q:::::::QQ::::::::Q111::::::111
+                QQ::::::::::::::Q 1::::::::::1
+                  QQ:::::::::::Q  1::::::::::1
+                    QQQQQQQQ::::QQ111111111111
+                            Q:::::Q           
+                             QQQQQQ  QUILIBRIUM.ONE                                                                                                                                
 
-# Step 1:Download Binary
-echo "⏳ Downloading New Release v1.4.18"
+                              
+===========================================================================
+                       ✨ QNODE SERVICE UPDATER ✨
+===========================================================================
+This script will update your Quilibrium node when running it as a service.
+It will run your ndoe form the release_autostart.sh file.
+
+Follow the guide at https://docs.quilibrium.one
+
+Made with 🔥 by LaMat - https://quilibrium.one
+===========================================================================
+
+Processing... ⏳
+
+EOF
+
+sleep 7  # Add a 7-second delay
+
+
+
+# Step 1: Stop the ceremonyclient service if it exists
+echo "⏳ Stopping the ceremonyclient service if it exists..."
+if systemctl is-active --quiet ceremonyclient && service ceremonyclient stop; then
+    echo "🔴 Service stopped successfully."
+else
+    echo "❌ Ceremonyclient service either does not exist or could not be stopped." >&2
+fi
+sleep 1
+
+# Step 2: Move to the ceremonyclient directory
+echo "Step 2: Moving to the ceremonyclient directory..."
+cd ~/ceremonyclient || { echo "❌ Error: Directory ~/ceremonyclient does not exist."; exit 1; }
+
+# Step 3: Discard local changes in release_autorun.sh
+echo "✅ Discarding local changes in release_autorun.sh..."
+git checkout -- node/release_autorun.sh
+
+# Function to install a package if it is not already installed
+install_package() {
+    echo "⏳ Installing $1..."
+    if apt-get install -y $1; then
+        echo "✅ $1 installed successfully."
+    else
+        echo "❌ Failed to install $1. You will have to do this manually."
+    fi
+}
+
+# Install cpulimit
+install_package cpulimit
+
+# Install gawk
+install_package gawk
+
+echo "✅ cpulimit and gawk are installed and up to date."
+
+
+# Step 4: Download Binary
+echo "⏳ Downloading New Release..."
+
+# Set the remote URL and download
 cd  ~/ceremonyclient
-
-git remote set-url origin https://source.quilibrium.com/quilibrium/ceremonyclient.git
-
+git remote set-url origin https://source.quilibrium.com/quilibrium/ceremonyclient.git || git remote set-url origin https://git.quilibrium-mirror.ch/agostbiro/ceremonyclient.git
 git pull
-git checkout release
+git checkout release-cdn
+
+echo "✅ Downloaded the latest changes successfully."
 
 # Get the current user's home directory
 HOME=$(eval echo ~$HOME_DIR)
@@ -26,11 +95,13 @@ HOME=$(eval echo ~$HOME_DIR)
 NODE_PATH="$HOME/ceremonyclient/node"
 EXEC_START="$NODE_PATH/release_autorun.sh"
 
-# Step 3:Re-Create Ceremonyclient Service
-echo "⏳ Re-Creating Ceremonyclient Service"
+# Step 5: Re-Create or Update Ceremonyclient Service
+echo "🔧 Rebuilding Ceremonyclient Service..."
 sleep 2  # Add a 2-second delay
-rm /lib/systemd/system/ceremonyclient.service
-sudo tee /lib/systemd/system/ceremonyclient.service > /dev/null <<EOF
+SERVICE_FILE="/lib/systemd/system/ceremonyclient.service"
+if [ ! -f "$SERVICE_FILE" ]; then
+    echo "📝 Creating new ceremonyclient service file..."
+    if ! sudo tee "$SERVICE_FILE" > /dev/null <<EOF
 [Unit]
 Description=Ceremony Client Go App Service
 
@@ -44,14 +115,39 @@ ExecStart=$EXEC_START
 [Install]
 WantedBy=multi-user.target
 EOF
+    then
+        echo "❌ Error: Failed to create ceremonyclient service file." >&2
+        exit 1
+    fi
+else
+    echo "🔍 Checking existing ceremonyclient service file..."
+    
+     # Check if the required lines exist, if they are different, or if CPUQuota exists
+    if ! grep -q "WorkingDirectory=$NODE_PATH" "$SERVICE_FILE" || ! grep -q "ExecStart=$EXEC_START" "$SERVICE_FILE" || grep -q '^CPUQuota=[0-9]*%' "$SERVICE_FILE"; then
+        echo "🔄 Updating existing ceremonyclient service file..."
+        # Replace the existing lines with new values
+        sudo sed -i "s|WorkingDirectory=.*|WorkingDirectory=$NODE_PATH|" "$SERVICE_FILE"
+        sudo sed -i "s|ExecStart=.*|ExecStart=$EXEC_START|" "$SERVICE_FILE"
+        # Remove any line containing CPUQuota=x%
+        if grep -q '^CPUQuota=[0-9]*%' "$SERVICE_FILE"; then
+            echo "✅ CPUQuota line found. Deleting..."
+            sudo sed -i '/^CPUQuota=[0-9]*%/d' "$SERVICE_FILE"
+            echo "✅ CPUQuota line deleted. You don't need this anymore!"
+        fi
+    else
+        echo "✅ No changes needed."
+    fi
+fi
 
-# Step 4:Start the ceremonyclient service
+# Step 6: Start the ceremonyclient service
 echo "✅ Starting Ceremonyclient Service"
 sleep 2  # Add a 2-second delay
-sudo systemctl daemon-reload
-sudo systemctl enable ceremonyclient
-sudo service ceremonyclient start
+systemctl daemon-reload
+systemctl enable ceremonyclient
+service ceremonyclient start
 
-# See the logs of the ceremonyclient service
-echo "🎉 Welcome to Quilibrium Ceremonyclient v1.4.18"
-echo "⏳ Please let it flow node logs at least 5 minutes then you can press CTRL + C to exit the logs."
+# Showing the node version and logs
+echo "🌟Your Qnode is now updated!"
+journalctl -u ceremonyclient -r --no-hostname  -n 1 -g "Quilibrium Node" -o cat
+echo ""
+echo "⏳ Showing the node log... (CTRL+C to exit)"
